// <auto-generated/>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Diagnostics;

namespace Sharezbold.ContentMigration
{
    public class Test
    {
        public void abc()
        {
            //ContentMigration.Lists l = new ContentMigration.Lists();
            //l.Credentials = new NetworkCredential("Administrator", "P@ssw0rd", "cssdev");

            //lists.AddList("ExportBuffer", "export buffer", 101); //document library
             
             
            /* 
            wsSites.Sites sites = new wsSites.Sites();
            sites.Credentials = new NetworkCredential("Administrator", "P@ssw0rd", "cssdev");

            Debug.WriteLine("bla: {0}", sites.ExportWeb("job1", "http://ss13-css-019/abcUrl/", "http://ss13-css-019/ExportBuffer", true, true, true, 10000000));
            */

            /*
            wsSites.Sites dest = new wsSites.Sites();
            dest.Url = "http://ss13-css-007/_vti_bin/Lists.asm";
            dest.Credentials = new NetworkCredential("Holzgethan", "FHWN2013!", "cssdev");
            string[] datapath = { "http://ss13-css-019/ExportBuffer/job1.cmp" };
            dest.ImportWeb("job1", "http://ss13-css-007", datapath, null, true, true);

            

            wsSites.Sites sites = new wsSites.Sites();
            sites.Credentials = new NetworkCredential("Administrator", "P@ssw0rd", "cssdev");
            Debug.WriteLine(sites.GetSite("http://ss13-css-019/abcUrl/"));
            */

            /*
            wsSiteData.SiteData siteData = new wsSiteData.SiteData();
            siteData.Credentials = new NetworkCredential("Administrator", "P@ssw0rd", "cssdev");

            string lastChangeID = "";
            string result = siteData.GetContent(wsSiteData.ObjectType.SiteCollection, "", "", "", false, false, ref lastChangeID);
            Debug.WriteLine(result);

            result = siteData.GetContent(wsSiteData.ObjectType.Site, "", "", "", true, false, ref lastChangeID);
            Debug.WriteLine(result);

            */


            //Debug.WriteLine("bla: {0}", sites.ExportWeb("job1", "http://ss13-css-019/abcUrl/", "http://ss13-css-019/ExportBuffer", true, true, true, 10000000));
            



        }
    }
}
