namespace SharezboldUI.Settings
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.18047
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.17929.
    // 


    /// <summary>
    /// Migration Settings class, fully serializable
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:xmlns:Sharezbold:SharepointMigration")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:xmlns:Sharezbold:SharepointMigration", IsNullable = false)]
    public partial class MigrationSettings
    {

        private string fromHostField;

        private string fromDomainField;

        private string fromUserNameField;

        private string fromPasswordField;

        private string toHostField;

        private string toDomainField;

        private string toUserNameField;

        private string toPasswordField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FromHost
        {
            get
            {
                return this.fromHostField;
            }
            set
            {
                this.fromHostField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FromDomain
        {
            get
            {
                return this.fromDomainField;
            }
            set
            {
                this.fromDomainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FromUserName
        {
            get
            {
                return this.fromUserNameField;
            }
            set
            {
                this.fromUserNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FromPassword
        {
            get
            {
                return this.fromPasswordField;
            }
            set
            {
                this.fromPasswordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToHost
        {
            get
            {
                return this.toHostField;
            }
            set
            {
                this.toHostField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToDomain
        {
            get
            {
                return this.toDomainField;
            }
            set
            {
                this.toDomainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToUserName
        {
            get
            {
                return this.toUserNameField;
            }
            set
            {
                this.toUserNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToPassword
        {
            get
            {
                return this.toPasswordField;
            }
            set
            {
                this.toPasswordField = value;
            }
        }
    }
}
