// <auto-generated/>
namespace Sharezbold
{
    /// <summary>
    /// MainForm created by the designer
    /// </summary>
    public partial class MainForm
    {
        /// <summary>
        /// necessarry designer variable
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Verwendete Ressourcen bereinigen.
        /// </summary>
        /// <param name="disposing">True, wenn verwaltete Ressourcen gelöscht werden sollen; andernfalls False.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Vom Windows Form-Designer generierter Code

        /// <summary>
        /// Designer method. DONT CHANGE THE CONTENT
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.dateiToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.loadMigrationProfileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.saveMigrationProfileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPageConfiguration = new System.Windows.Forms.TabPage();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.buttonConfigurationNext = new System.Windows.Forms.Button();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.label5 = new System.Windows.Forms.Label();
            this.textBoxToHost = new System.Windows.Forms.TextBox();
            this.textBoxToUserName = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.textBoxToDomain = new System.Windows.Forms.TextBox();
            this.textBoxToPassword = new System.Windows.Forms.TextBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.label1 = new System.Windows.Forms.Label();
            this.textBoxFromHost = new System.Windows.Forms.TextBox();
            this.textBoxFromUserName = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.textBoxFromDomain = new System.Windows.Forms.TextBox();
            this.textBoxFromPassword = new System.Windows.Forms.TextBox();
            this.tabPageContentSelection = new System.Windows.Forms.TabPage();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.treeViewContentSelection = new System.Windows.Forms.TreeView();
            this.imageListTreeView = new System.Windows.Forms.ImageList(this.components);
            this.buttonStartMigration = new System.Windows.Forms.Button();
            this.tabPageMigrationProgress = new System.Windows.Forms.TabPage();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.listBoxMigrationLog = new System.Windows.Forms.ListBox();
            this.button1 = new System.Windows.Forms.Button();
            this.tabPageElementsMigration = new System.Windows.Forms.TabPage();
            this.checkBoxContentTypeMigration = new System.Windows.Forms.CheckBox();
            this.checkBoxSiteColumns = new System.Windows.Forms.CheckBox();
            this.checkBoxPermissionLevels = new System.Windows.Forms.CheckBox();
            this.checkBoxUsers = new System.Windows.Forms.CheckBox();
            this.checkBoxGroups = new System.Windows.Forms.CheckBox();
            this.checkBoxWorkflows = new System.Windows.Forms.CheckBox();
            this.label9 = new System.Windows.Forms.Label();
            this.buttonStartElementsMigration = new System.Windows.Forms.Button();
            this.tabControl1.SuspendLayout();
            this.tabPageConfiguration.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.tabPageContentSelection.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.tabPageMigrationProgress.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.tabPageElementsMigration.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(1031, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // dateiToolStripMenuItem
            // 
            this.dateiToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.loadMigrationProfileToolStripMenuItem,
            this.saveMigrationProfileToolStripMenuItem,
            this.exitToolStripMenuItem});
            this.dateiToolStripMenuItem.Name = "dateiToolStripMenuItem";
            this.dateiToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.dateiToolStripMenuItem.Text = "Datei";
            // 
            // loadMigrationProfileToolStripMenuItem
            // 
            this.loadMigrationProfileToolStripMenuItem.Name = "loadMigrationProfileToolStripMenuItem";
            this.loadMigrationProfileToolStripMenuItem.Size = new System.Drawing.Size(192, 22);
            this.loadMigrationProfileToolStripMenuItem.Text = "Load Migration profile";
            this.loadMigrationProfileToolStripMenuItem.Click += new System.EventHandler(this.LoadMigrationProfileToolStripMenuItem_Click);
            // 
            // saveMigrationProfileToolStripMenuItem
            // 
            this.saveMigrationProfileToolStripMenuItem.Name = "saveMigrationProfileToolStripMenuItem";
            this.saveMigrationProfileToolStripMenuItem.Size = new System.Drawing.Size(192, 22);
            this.saveMigrationProfileToolStripMenuItem.Text = "Save Migration profile";
            this.saveMigrationProfileToolStripMenuItem.Click += new System.EventHandler(this.SaveMigrationProfileToolStripMenuItem_Click);
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(192, 22);
            this.exitToolStripMenuItem.Text = "Beenden";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.ExitToolStripMenuItem_Click);
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPageConfiguration);
            this.tabControl1.Controls.Add(this.tabPageContentSelection);
            this.tabControl1.Controls.Add(this.tabPageMigrationProgress);
            this.tabControl1.Controls.Add(this.tabPageElementsMigration);
            this.tabControl1.Location = new System.Drawing.Point(0, 27);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(1031, 406);
            this.tabControl1.TabIndex = 2;
            // 
            // tabPageConfiguration
            // 
            this.tabPageConfiguration.Controls.Add(this.groupBox3);
            this.tabPageConfiguration.Location = new System.Drawing.Point(4, 22);
            this.tabPageConfiguration.Name = "tabPageConfiguration";
            this.tabPageConfiguration.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageConfiguration.Size = new System.Drawing.Size(1023, 380);
            this.tabPageConfiguration.TabIndex = 0;
            this.tabPageConfiguration.Text = "Configuration";
            this.tabPageConfiguration.UseVisualStyleBackColor = true;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.buttonConfigurationNext);
            this.groupBox3.Controls.Add(this.groupBox2);
            this.groupBox3.Controls.Add(this.groupBox1);
            this.groupBox3.Location = new System.Drawing.Point(0, 0);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(1020, 375);
            this.groupBox3.TabIndex = 4;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Configuration";
            // 
            // buttonConfigurationNext
            // 
            this.buttonConfigurationNext.Location = new System.Drawing.Point(914, 346);
            this.buttonConfigurationNext.Name = "buttonConfigurationNext";
            this.buttonConfigurationNext.Size = new System.Drawing.Size(100, 23);
            this.buttonConfigurationNext.TabIndex = 2;
            this.buttonConfigurationNext.Text = "next";
            this.buttonConfigurationNext.UseVisualStyleBackColor = true;
            this.buttonConfigurationNext.Click += new System.EventHandler(this.ButtonConfigurationNext_Click);
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.tableLayoutPanel2);
            this.groupBox2.Location = new System.Drawing.Point(14, 186);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(320, 150);
            this.groupBox2.TabIndex = 3;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Destination Configuration";
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel2.Controls.Add(this.label5, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.textBoxToHost, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.textBoxToUserName, 1, 1);
            this.tableLayoutPanel2.Controls.Add(this.label6, 0, 1);
            this.tableLayoutPanel2.Controls.Add(this.label7, 0, 2);
            this.tableLayoutPanel2.Controls.Add(this.label8, 0, 3);
            this.tableLayoutPanel2.Controls.Add(this.textBoxToDomain, 1, 2);
            this.tableLayoutPanel2.Controls.Add(this.textBoxToPassword, 1, 3);
            this.tableLayoutPanel2.Location = new System.Drawing.Point(5, 20);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 4;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel2.Size = new System.Drawing.Size(292, 109);
            this.tableLayoutPanel2.TabIndex = 1;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(3, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(56, 13);
            this.label5.TabIndex = 0;
            this.label5.Text = "Host:        ";
            // 
            // textBoxToHost
            // 
            this.textBoxToHost.Location = new System.Drawing.Point(67, 3);
            this.textBoxToHost.Name = "textBoxToHost";
            this.textBoxToHost.Size = new System.Drawing.Size(200, 20);
            this.textBoxToHost.TabIndex = 2;
            // 
            // textBoxToUserName
            // 
            this.textBoxToUserName.Location = new System.Drawing.Point(67, 29);
            this.textBoxToUserName.Name = "textBoxToUserName";
            this.textBoxToUserName.Size = new System.Drawing.Size(200, 20);
            this.textBoxToUserName.TabIndex = 3;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(3, 26);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(58, 13);
            this.label6.TabIndex = 1;
            this.label6.Text = "Username:";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(3, 52);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(46, 13);
            this.label7.TabIndex = 4;
            this.label7.Text = "Domain:";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(3, 78);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(56, 13);
            this.label8.TabIndex = 5;
            this.label8.Text = "Password:";
            // 
            // textBoxToDomain
            // 
            this.textBoxToDomain.Location = new System.Drawing.Point(67, 55);
            this.textBoxToDomain.Name = "textBoxToDomain";
            this.textBoxToDomain.Size = new System.Drawing.Size(200, 20);
            this.textBoxToDomain.TabIndex = 6;
            // 
            // textBoxToPassword
            // 
            this.textBoxToPassword.Location = new System.Drawing.Point(67, 81);
            this.textBoxToPassword.Name = "textBoxToPassword";
            this.textBoxToPassword.PasswordChar = '*';
            this.textBoxToPassword.Size = new System.Drawing.Size(200, 20);
            this.textBoxToPassword.TabIndex = 7;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.tableLayoutPanel1);
            this.groupBox1.Location = new System.Drawing.Point(14, 19);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(320, 150);
            this.groupBox1.TabIndex = 1;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Source Configuration";
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.Controls.Add(this.label1, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.textBoxFromHost, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.textBoxFromUserName, 1, 1);
            this.tableLayoutPanel1.Controls.Add(this.label2, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.label3, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.label4, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.textBoxFromDomain, 1, 2);
            this.tableLayoutPanel1.Controls.Add(this.textBoxFromPassword, 1, 3);
            this.tableLayoutPanel1.Location = new System.Drawing.Point(5, 20);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 4;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.Size = new System.Drawing.Size(292, 109);
            this.tableLayoutPanel1.TabIndex = 0;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(3, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(77, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Site Collection:";
            // 
            // textBoxFromHost
            // 
            this.textBoxFromHost.Location = new System.Drawing.Point(86, 3);
            this.textBoxFromHost.Name = "textBoxFromHost";
            this.textBoxFromHost.Size = new System.Drawing.Size(200, 20);
            this.textBoxFromHost.TabIndex = 2;
            // 
            // textBoxFromUserName
            // 
            this.textBoxFromUserName.Location = new System.Drawing.Point(86, 29);
            this.textBoxFromUserName.Name = "textBoxFromUserName";
            this.textBoxFromUserName.Size = new System.Drawing.Size(200, 20);
            this.textBoxFromUserName.TabIndex = 3;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(3, 26);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(58, 13);
            this.label2.TabIndex = 1;
            this.label2.Text = "Username:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(3, 52);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(46, 13);
            this.label3.TabIndex = 4;
            this.label3.Text = "Domain:";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(3, 78);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(56, 13);
            this.label4.TabIndex = 5;
            this.label4.Text = "Password:";
            // 
            // textBoxFromDomain
            // 
            this.textBoxFromDomain.Location = new System.Drawing.Point(86, 55);
            this.textBoxFromDomain.Name = "textBoxFromDomain";
            this.textBoxFromDomain.Size = new System.Drawing.Size(200, 20);
            this.textBoxFromDomain.TabIndex = 6;
            // 
            // textBoxFromPassword
            // 
            this.textBoxFromPassword.Location = new System.Drawing.Point(86, 81);
            this.textBoxFromPassword.Name = "textBoxFromPassword";
            this.textBoxFromPassword.PasswordChar = '*';
            this.textBoxFromPassword.Size = new System.Drawing.Size(200, 20);
            this.textBoxFromPassword.TabIndex = 7;
            // 
            // tabPageContentSelection
            // 
            this.tabPageContentSelection.Controls.Add(this.groupBox4);
            this.tabPageContentSelection.Location = new System.Drawing.Point(4, 22);
            this.tabPageContentSelection.Name = "tabPageContentSelection";
            this.tabPageContentSelection.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageContentSelection.Size = new System.Drawing.Size(1023, 380);
            this.tabPageContentSelection.TabIndex = 1;
            this.tabPageContentSelection.Text = "Content Selection";
            this.tabPageContentSelection.UseVisualStyleBackColor = true;
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.treeViewContentSelection);
            this.groupBox4.Controls.Add(this.buttonStartMigration);
            this.groupBox4.Location = new System.Drawing.Point(0, 0);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(1020, 375);
            this.groupBox4.TabIndex = 3;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Content Selection";
            // 
            // treeViewContentSelection
            // 
            this.treeViewContentSelection.ImageIndex = 0;
            this.treeViewContentSelection.ImageList = this.imageListTreeView;
            this.treeViewContentSelection.Location = new System.Drawing.Point(8, 19);
            this.treeViewContentSelection.Name = "treeViewContentSelection";
            this.treeViewContentSelection.SelectedImageIndex = 0;
            this.treeViewContentSelection.Size = new System.Drawing.Size(345, 316);
            this.treeViewContentSelection.TabIndex = 0;
            // 
            // imageListTreeView
            // 
            this.imageListTreeView.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageListTreeView.ImageStream")));
            this.imageListTreeView.TransparentColor = System.Drawing.Color.Transparent;
            this.imageListTreeView.Images.SetKeyName(0, "sitecollection.png");
            this.imageListTreeView.Images.SetKeyName(1, "site.png");
            this.imageListTreeView.Images.SetKeyName(2, "list.gif");
            this.imageListTreeView.Images.SetKeyName(3, "library.png");
            // 
            // buttonStartMigration
            // 
            this.buttonStartMigration.Location = new System.Drawing.Point(914, 346);
            this.buttonStartMigration.Name = "buttonStartMigration";
            this.buttonStartMigration.Size = new System.Drawing.Size(100, 23);
            this.buttonStartMigration.TabIndex = 1;
            this.buttonStartMigration.Text = "start migration";
            this.buttonStartMigration.UseVisualStyleBackColor = true;
            this.buttonStartMigration.Click += new System.EventHandler(this.ButtonStartMigration_Click);
            // 
            // tabPageMigrationProgress
            // 
            this.tabPageMigrationProgress.Controls.Add(this.groupBox5);
            this.tabPageMigrationProgress.Location = new System.Drawing.Point(4, 22);
            this.tabPageMigrationProgress.Name = "tabPageMigrationProgress";
            this.tabPageMigrationProgress.Size = new System.Drawing.Size(1023, 380);
            this.tabPageMigrationProgress.TabIndex = 2;
            this.tabPageMigrationProgress.Text = "Migration Progress";
            this.tabPageMigrationProgress.UseVisualStyleBackColor = true;
            // 
            // groupBox5
            // 
            this.groupBox5.Controls.Add(this.listBoxMigrationLog);
            this.groupBox5.Controls.Add(this.button1);
            this.groupBox5.Location = new System.Drawing.Point(0, 0);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(1020, 375);
            this.groupBox5.TabIndex = 3;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Migration Progress";
            // 
            // listBoxMigrationLog
            // 
            this.listBoxMigrationLog.FormattingEnabled = true;
            this.listBoxMigrationLog.Location = new System.Drawing.Point(8, 19);
            this.listBoxMigrationLog.Name = "listBoxMigrationLog";
            this.listBoxMigrationLog.Size = new System.Drawing.Size(1006, 316);
            this.listBoxMigrationLog.TabIndex = 0;
            // 
            // button1
            // 
            this.button1.Enabled = false;
            this.button1.Location = new System.Drawing.Point(914, 346);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(100, 23);
            this.button1.TabIndex = 2;
            this.button1.Text = "Finish & Exit";
            this.button1.UseVisualStyleBackColor = true;
            // 
            // tabPageElementsMigration
            // 
            this.tabPageElementsMigration.Controls.Add(this.buttonStartElementsMigration);
            this.tabPageElementsMigration.Controls.Add(this.label9);
            this.tabPageElementsMigration.Controls.Add(this.checkBoxWorkflows);
            this.tabPageElementsMigration.Controls.Add(this.checkBoxGroups);
            this.tabPageElementsMigration.Controls.Add(this.checkBoxUsers);
            this.tabPageElementsMigration.Controls.Add(this.checkBoxPermissionLevels);
            this.tabPageElementsMigration.Controls.Add(this.checkBoxSiteColumns);
            this.tabPageElementsMigration.Controls.Add(this.checkBoxContentTypeMigration);
            this.tabPageElementsMigration.Location = new System.Drawing.Point(4, 22);
            this.tabPageElementsMigration.Name = "tabPageElementsMigration";
            this.tabPageElementsMigration.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageElementsMigration.Size = new System.Drawing.Size(1023, 380);
            this.tabPageElementsMigration.TabIndex = 3;
            this.tabPageElementsMigration.Text = "Elements Migration";
            this.tabPageElementsMigration.UseVisualStyleBackColor = true;
            // 
            // checkBoxContentTypeMigration
            // 
            this.checkBoxContentTypeMigration.AutoSize = true;
            this.checkBoxContentTypeMigration.Location = new System.Drawing.Point(32, 94);
            this.checkBoxContentTypeMigration.Name = "checkBoxContentTypeMigration";
            this.checkBoxContentTypeMigration.Size = new System.Drawing.Size(130, 17);
            this.checkBoxContentTypeMigration.TabIndex = 0;
            this.checkBoxContentTypeMigration.Text = "Migrate ContentTypes";
            this.checkBoxContentTypeMigration.UseVisualStyleBackColor = true;
            this.checkBoxContentTypeMigration.CheckedChanged += new System.EventHandler(this.checkBoxContentTypeMigration_CheckedChanged);
            // 
            // checkBoxSiteColumns
            // 
            this.checkBoxSiteColumns.AutoSize = true;
            this.checkBoxSiteColumns.Location = new System.Drawing.Point(32, 135);
            this.checkBoxSiteColumns.Name = "checkBoxSiteColumns";
            this.checkBoxSiteColumns.Size = new System.Drawing.Size(125, 17);
            this.checkBoxSiteColumns.TabIndex = 1;
            this.checkBoxSiteColumns.Text = "Migrate Site-Columns";
            this.checkBoxSiteColumns.UseVisualStyleBackColor = true;
            // 
            // checkBoxPermissionLevels
            // 
            this.checkBoxPermissionLevels.AutoSize = true;
            this.checkBoxPermissionLevels.Location = new System.Drawing.Point(32, 176);
            this.checkBoxPermissionLevels.Name = "checkBoxPermissionLevels";
            this.checkBoxPermissionLevels.Size = new System.Drawing.Size(148, 17);
            this.checkBoxPermissionLevels.TabIndex = 2;
            this.checkBoxPermissionLevels.Text = "Migrate Permission-Levels";
            this.checkBoxPermissionLevels.UseVisualStyleBackColor = true;
            // 
            // checkBoxUsers
            // 
            this.checkBoxUsers.AutoSize = true;
            this.checkBoxUsers.Location = new System.Drawing.Point(32, 213);
            this.checkBoxUsers.Name = "checkBoxUsers";
            this.checkBoxUsers.Size = new System.Drawing.Size(91, 17);
            this.checkBoxUsers.TabIndex = 3;
            this.checkBoxUsers.Text = "Migrate Users";
            this.checkBoxUsers.UseVisualStyleBackColor = true;
            // 
            // checkBoxGroups
            // 
            this.checkBoxGroups.AutoSize = true;
            this.checkBoxGroups.Location = new System.Drawing.Point(32, 251);
            this.checkBoxGroups.Name = "checkBoxGroups";
            this.checkBoxGroups.Size = new System.Drawing.Size(98, 17);
            this.checkBoxGroups.TabIndex = 4;
            this.checkBoxGroups.Text = "Migrate Groups";
            this.checkBoxGroups.UseVisualStyleBackColor = true;
            // 
            // checkBoxWorkflows
            // 
            this.checkBoxWorkflows.AutoSize = true;
            this.checkBoxWorkflows.Location = new System.Drawing.Point(32, 288);
            this.checkBoxWorkflows.Name = "checkBoxWorkflows";
            this.checkBoxWorkflows.Size = new System.Drawing.Size(114, 17);
            this.checkBoxWorkflows.TabIndex = 5;
            this.checkBoxWorkflows.Text = "Migrate Workflows";
            this.checkBoxWorkflows.UseVisualStyleBackColor = true;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(32, 25);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(207, 24);
            this.label9.TabIndex = 6;
            this.label9.Text = "Migrate the Elements";
            // 
            // buttonStartElementsMigration
            // 
            this.buttonStartElementsMigration.Location = new System.Drawing.Point(32, 336);
            this.buttonStartElementsMigration.Name = "buttonStartElementsMigration";
            this.buttonStartElementsMigration.Size = new System.Drawing.Size(91, 23);
            this.buttonStartElementsMigration.TabIndex = 7;
            this.buttonStartElementsMigration.Text = "Start Migration";
            this.buttonStartElementsMigration.UseVisualStyleBackColor = true;
            this.buttonStartElementsMigration.Click += new System.EventHandler(this.buttonStartElementsMigration_Click);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1031, 433);
            this.Controls.Add(this.tabControl1);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "MainForm";
            this.Text = "Sharezbold-UI";
            this.tabControl1.ResumeLayout(false);
            this.tabPageConfiguration.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            this.tabPageContentSelection.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.tabPageMigrationProgress.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.tabPageElementsMigration.ResumeLayout(false);
            this.tabPageElementsMigration.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem dateiToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox textBoxFromHost;
        private System.Windows.Forms.TextBox textBoxFromUserName;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox textBoxFromDomain;
        private System.Windows.Forms.TextBox textBoxFromPassword;
        private System.Windows.Forms.Button buttonConfigurationNext;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TreeView treeViewContentSelection;
        private System.Windows.Forms.ListBox listBoxMigrationLog;
        private System.Windows.Forms.Button buttonStartMigration;
        private System.Windows.Forms.ToolStripMenuItem loadMigrationProfileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem saveMigrationProfileToolStripMenuItem;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox textBoxToHost;
        private System.Windows.Forms.TextBox textBoxToUserName;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox textBoxToDomain;
        private System.Windows.Forms.TextBox textBoxToPassword;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPageConfiguration;
        private System.Windows.Forms.TabPage tabPageContentSelection;
        private System.Windows.Forms.TabPage tabPageMigrationProgress;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.ImageList imageListTreeView;
        private System.Windows.Forms.TabPage tabPageElementsMigration;
        private System.Windows.Forms.CheckBox checkBoxWorkflows;
        private System.Windows.Forms.CheckBox checkBoxGroups;
        private System.Windows.Forms.CheckBox checkBoxUsers;
        private System.Windows.Forms.CheckBox checkBoxPermissionLevels;
        private System.Windows.Forms.CheckBox checkBoxSiteColumns;
        private System.Windows.Forms.CheckBox checkBoxContentTypeMigration;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Button buttonStartElementsMigration;
    }
}