// <auto-generated/>
namespace Sharezbold
{
    /// <summary>
    /// MainForm created by the designer
    /// </summary>
    public partial class MainForm
    {
        /// <summary>
        /// necessarry designer variable
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Verwendete Ressourcen bereinigen.
        /// </summary>
        /// <param name="disposing">True, wenn verwaltete Ressourcen gelöscht werden sollen; andernfalls False.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Vom Windows Form-Designer generierter Code

        /// <summary>
        /// Designer method. DONT CHANGE THE CONTENT
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.saveMigrationProfileToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
            this.loadMigrationProfileToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
            this.closeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.dateiToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.loadMigrationProfileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.saveMigrationProfileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tabControMain = new System.Windows.Forms.TabControl();
            this.tabPageConfiguration = new System.Windows.Forms.TabPage();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.buttonConfigurationNext = new System.Windows.Forms.Button();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.textBoxToHost = new System.Windows.Forms.TextBox();
            this.textBoxToUserName = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.textBoxToDomain = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.textBoxToPassword = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.textBoxFromHost = new System.Windows.Forms.TextBox();
            this.textBoxFromUserName = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.textBoxFromDomain = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.textBoxFromPassword = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.tabPageContentSelection = new System.Windows.Forms.TabPage();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.buttonConfigureMigration = new System.Windows.Forms.Button();
            this.treeViewContentSelection = new System.Windows.Forms.TreeView();
            this.imageListTreeView = new System.Windows.Forms.ImageList(this.components);
            this.tabPageMigrationPreparation = new System.Windows.Forms.TabPage();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.buttonStartMigration = new System.Windows.Forms.Button();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.listViewMigrationContent = new System.Windows.Forms.ListView();
            this.imageListMigrationContent = new System.Windows.Forms.ImageList(this.components);
            this.tabPageMigrationProgress = new System.Windows.Forms.TabPage();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.listBoxMigrationLog = new System.Windows.Forms.ListBox();
            this.button1 = new System.Windows.Forms.Button();
            this.tabPageMigrationElements = new System.Windows.Forms.TabPage();
            this.checkBoxMigrateContentType = new System.Windows.Forms.CheckBox();
            this.buttonElementsMigration = new System.Windows.Forms.Button();
            this.labelMigrationElementsHeader = new System.Windows.Forms.Label();
            this.checkBoxMigrateUser = new System.Windows.Forms.CheckBox();
            this.checkBoxMigrateGroup = new System.Windows.Forms.CheckBox();
            this.checkBoxMigrateSiteColumns = new System.Windows.Forms.CheckBox();
            this.checkBoxMigrateWorkflow = new System.Windows.Forms.CheckBox();
            this.checkBoxMigratePermissionlevels = new System.Windows.Forms.CheckBox();
            this.menuStrip1.SuspendLayout();
            this.tabControMain.SuspendLayout();
            this.tabPageConfiguration.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tabPageContentSelection.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.tabPageMigrationPreparation.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.tabPageMigrationProgress.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.tabPageMigrationElements.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(1031, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.saveMigrationProfileToolStripMenuItem1,
            this.loadMigrationProfileToolStripMenuItem1,
            this.closeToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "File";
            // 
            // saveMigrationProfileToolStripMenuItem1
            // 
            this.saveMigrationProfileToolStripMenuItem1.Name = "saveMigrationProfileToolStripMenuItem1";
            this.saveMigrationProfileToolStripMenuItem1.Size = new System.Drawing.Size(204, 22);
            this.saveMigrationProfileToolStripMenuItem1.Text = "Save Migration Profile ...";
            this.saveMigrationProfileToolStripMenuItem1.Click += new System.EventHandler(this.SaveMigrationProfileToolStripMenuItem_Click);
            // 
            // loadMigrationProfileToolStripMenuItem1
            // 
            this.loadMigrationProfileToolStripMenuItem1.Name = "loadMigrationProfileToolStripMenuItem1";
            this.loadMigrationProfileToolStripMenuItem1.Size = new System.Drawing.Size(204, 22);
            this.loadMigrationProfileToolStripMenuItem1.Text = "Load Migration Profile ...";
            this.loadMigrationProfileToolStripMenuItem1.Click += new System.EventHandler(this.LoadMigrationProfileToolStripMenuItem_Click);
            // 
            // closeToolStripMenuItem
            // 
            this.closeToolStripMenuItem.Name = "closeToolStripMenuItem";
            this.closeToolStripMenuItem.Size = new System.Drawing.Size(204, 22);
            this.closeToolStripMenuItem.Text = "Close";
            this.closeToolStripMenuItem.Click += new System.EventHandler(this.ExitToolStripMenuItem_Click);
            // 
            // dateiToolStripMenuItem
            // 
            this.dateiToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.loadMigrationProfileToolStripMenuItem,
            this.saveMigrationProfileToolStripMenuItem,
            this.exitToolStripMenuItem});
            this.dateiToolStripMenuItem.Name = "dateiToolStripMenuItem";
            this.dateiToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.dateiToolStripMenuItem.Text = "Datei";
            // 
            // loadMigrationProfileToolStripMenuItem
            // 
            this.loadMigrationProfileToolStripMenuItem.Name = "loadMigrationProfileToolStripMenuItem";
            this.loadMigrationProfileToolStripMenuItem.Size = new System.Drawing.Size(192, 22);
            this.loadMigrationProfileToolStripMenuItem.Text = "Load Migration profile";
            this.loadMigrationProfileToolStripMenuItem.Click += new System.EventHandler(this.LoadMigrationProfileToolStripMenuItem_Click);
            // 
            // saveMigrationProfileToolStripMenuItem
            // 
            this.saveMigrationProfileToolStripMenuItem.Name = "saveMigrationProfileToolStripMenuItem";
            this.saveMigrationProfileToolStripMenuItem.Size = new System.Drawing.Size(192, 22);
            this.saveMigrationProfileToolStripMenuItem.Text = "Save Migration profile";
            this.saveMigrationProfileToolStripMenuItem.Click += new System.EventHandler(this.SaveMigrationProfileToolStripMenuItem_Click);
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(192, 22);
            this.exitToolStripMenuItem.Text = "Beenden";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.ExitToolStripMenuItem_Click);
            // 
            // tabControMain
            // 
            this.tabControMain.Controls.Add(this.tabPageConfiguration);
            this.tabControMain.Controls.Add(this.tabPageContentSelection);
            this.tabControMain.Controls.Add(this.tabPageMigrationPreparation);
            this.tabControMain.Controls.Add(this.tabPageMigrationProgress);
            this.tabControMain.Controls.Add(this.tabPageMigrationElements);
            this.tabControMain.Location = new System.Drawing.Point(0, 27);
            this.tabControMain.Name = "tabControMain";
            this.tabControMain.SelectedIndex = 0;
            this.tabControMain.Size = new System.Drawing.Size(1031, 406);
            this.tabControMain.TabIndex = 2;
            // 
            // tabPageConfiguration
            // 
            this.tabPageConfiguration.Controls.Add(this.groupBox3);
            this.tabPageConfiguration.Location = new System.Drawing.Point(4, 22);
            this.tabPageConfiguration.Name = "tabPageConfiguration";
            this.tabPageConfiguration.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageConfiguration.Size = new System.Drawing.Size(1023, 380);
            this.tabPageConfiguration.TabIndex = 0;
            this.tabPageConfiguration.Text = "Configuration";
            this.tabPageConfiguration.UseVisualStyleBackColor = true;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.buttonConfigurationNext);
            this.groupBox3.Controls.Add(this.groupBox2);
            this.groupBox3.Controls.Add(this.groupBox1);
            this.groupBox3.Location = new System.Drawing.Point(0, 0);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(1020, 375);
            this.groupBox3.TabIndex = 4;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Configuration";
            // 
            // buttonConfigurationNext
            // 
            this.buttonConfigurationNext.Location = new System.Drawing.Point(914, 346);
            this.buttonConfigurationNext.Name = "buttonConfigurationNext";
            this.buttonConfigurationNext.Size = new System.Drawing.Size(100, 23);
            this.buttonConfigurationNext.TabIndex = 2;
            this.buttonConfigurationNext.Text = "next";
            this.buttonConfigurationNext.UseVisualStyleBackColor = true;
            this.buttonConfigurationNext.Click += new System.EventHandler(this.ButtonConfigurationNext_Click);
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.textBoxToHost);
            this.groupBox2.Controls.Add(this.textBoxToUserName);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.textBoxToDomain);
            this.groupBox2.Controls.Add(this.label8);
            this.groupBox2.Controls.Add(this.textBoxToPassword);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Controls.Add(this.label6);
            this.groupBox2.Location = new System.Drawing.Point(14, 186);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(320, 150);
            this.groupBox2.TabIndex = 3;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Destination Configuration";
            // 
            // textBoxToHost
            // 
            this.textBoxToHost.Location = new System.Drawing.Point(100, 32);
            this.textBoxToHost.Name = "textBoxToHost";
            this.textBoxToHost.Size = new System.Drawing.Size(200, 20);
            this.textBoxToHost.TabIndex = 2;
            // 
            // textBoxToUserName
            // 
            this.textBoxToUserName.Location = new System.Drawing.Point(100, 58);
            this.textBoxToUserName.Name = "textBoxToUserName";
            this.textBoxToUserName.Size = new System.Drawing.Size(200, 20);
            this.textBoxToUserName.TabIndex = 3;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(17, 32);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(56, 13);
            this.label5.TabIndex = 0;
            this.label5.Text = "Host:        ";
            // 
            // textBoxToDomain
            // 
            this.textBoxToDomain.Location = new System.Drawing.Point(100, 84);
            this.textBoxToDomain.Name = "textBoxToDomain";
            this.textBoxToDomain.Size = new System.Drawing.Size(200, 20);
            this.textBoxToDomain.TabIndex = 6;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(17, 110);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(56, 13);
            this.label8.TabIndex = 5;
            this.label8.Text = "Password:";
            // 
            // textBoxToPassword
            // 
            this.textBoxToPassword.Location = new System.Drawing.Point(100, 110);
            this.textBoxToPassword.Name = "textBoxToPassword";
            this.textBoxToPassword.PasswordChar = '*';
            this.textBoxToPassword.Size = new System.Drawing.Size(200, 20);
            this.textBoxToPassword.TabIndex = 7;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(17, 84);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(46, 13);
            this.label7.TabIndex = 4;
            this.label7.Text = "Domain:";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(17, 58);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(58, 13);
            this.label6.TabIndex = 1;
            this.label6.Text = "Username:";
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.textBoxFromHost);
            this.groupBox1.Controls.Add(this.textBoxFromUserName);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.textBoxFromDomain);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.textBoxFromPassword);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Location = new System.Drawing.Point(14, 19);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(320, 150);
            this.groupBox1.TabIndex = 1;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Source Configuration";
            // 
            // textBoxFromHost
            // 
            this.textBoxFromHost.Location = new System.Drawing.Point(100, 28);
            this.textBoxFromHost.Name = "textBoxFromHost";
            this.textBoxFromHost.Size = new System.Drawing.Size(200, 20);
            this.textBoxFromHost.TabIndex = 2;
            // 
            // textBoxFromUserName
            // 
            this.textBoxFromUserName.Location = new System.Drawing.Point(100, 54);
            this.textBoxFromUserName.Name = "textBoxFromUserName";
            this.textBoxFromUserName.Size = new System.Drawing.Size(200, 20);
            this.textBoxFromUserName.TabIndex = 3;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(17, 28);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(77, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Site Collection:";
            // 
            // textBoxFromDomain
            // 
            this.textBoxFromDomain.Location = new System.Drawing.Point(100, 80);
            this.textBoxFromDomain.Name = "textBoxFromDomain";
            this.textBoxFromDomain.Size = new System.Drawing.Size(200, 20);
            this.textBoxFromDomain.TabIndex = 6;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(17, 106);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(56, 13);
            this.label4.TabIndex = 5;
            this.label4.Text = "Password:";
            // 
            // textBoxFromPassword
            // 
            this.textBoxFromPassword.Location = new System.Drawing.Point(100, 106);
            this.textBoxFromPassword.Name = "textBoxFromPassword";
            this.textBoxFromPassword.PasswordChar = '*';
            this.textBoxFromPassword.Size = new System.Drawing.Size(200, 20);
            this.textBoxFromPassword.TabIndex = 7;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(17, 80);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(46, 13);
            this.label3.TabIndex = 4;
            this.label3.Text = "Domain:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(17, 54);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(58, 13);
            this.label2.TabIndex = 1;
            this.label2.Text = "Username:";
            // 
            // tabPageContentSelection
            // 
            this.tabPageContentSelection.Controls.Add(this.groupBox4);
            this.tabPageContentSelection.Location = new System.Drawing.Point(4, 22);
            this.tabPageContentSelection.Name = "tabPageContentSelection";
            this.tabPageContentSelection.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageContentSelection.Size = new System.Drawing.Size(1023, 380);
            this.tabPageContentSelection.TabIndex = 1;
            this.tabPageContentSelection.Text = "Content Selection";
            this.tabPageContentSelection.UseVisualStyleBackColor = true;
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.buttonConfigureMigration);
            this.groupBox4.Controls.Add(this.treeViewContentSelection);
            this.groupBox4.Location = new System.Drawing.Point(0, 0);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(1020, 375);
            this.groupBox4.TabIndex = 3;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Content Selection";
            // 
            // buttonConfigureMigration
            // 
            this.buttonConfigureMigration.Location = new System.Drawing.Point(899, 346);
            this.buttonConfigureMigration.Name = "buttonConfigureMigration";
            this.buttonConfigureMigration.Size = new System.Drawing.Size(115, 23);
            this.buttonConfigureMigration.TabIndex = 1;
            this.buttonConfigureMigration.Text = "Configure Migration";
            this.buttonConfigureMigration.UseVisualStyleBackColor = true;
            this.buttonConfigureMigration.Click += new System.EventHandler(this.ButtonConfigureMigration_Click);
            // 
            // treeViewContentSelection
            // 
            this.treeViewContentSelection.ImageIndex = 0;
            this.treeViewContentSelection.ImageList = this.imageListTreeView;
            this.treeViewContentSelection.Location = new System.Drawing.Point(8, 19);
            this.treeViewContentSelection.Name = "treeViewContentSelection";
            this.treeViewContentSelection.SelectedImageIndex = 0;
            this.treeViewContentSelection.Size = new System.Drawing.Size(345, 316);
            this.treeViewContentSelection.TabIndex = 0;
            this.treeViewContentSelection.BeforeCheck += new System.Windows.Forms.TreeViewCancelEventHandler(this.TreeViewContentSelection_DisableOrEnableEvent);
            this.treeViewContentSelection.AfterCheck += new System.Windows.Forms.TreeViewEventHandler(this.TreeViewContentSelection_AfterCheck);
            this.treeViewContentSelection.BeforeCollapse += new System.Windows.Forms.TreeViewCancelEventHandler(this.TreeViewContentSelection_DisableOrEnableEvent);
            this.treeViewContentSelection.BeforeExpand += new System.Windows.Forms.TreeViewCancelEventHandler(this.TreeViewContentSelection_DisableOrEnableEvent);
            this.treeViewContentSelection.BeforeSelect += new System.Windows.Forms.TreeViewCancelEventHandler(this.TreeViewContentSelection_DisableOrEnableEvent);
            // 
            // imageListTreeView
            // 
            this.imageListTreeView.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageListTreeView.ImageStream")));
            this.imageListTreeView.TransparentColor = System.Drawing.Color.Transparent;
            this.imageListTreeView.Images.SetKeyName(0, "sitecollection.png");
            this.imageListTreeView.Images.SetKeyName(1, "site.png");
            this.imageListTreeView.Images.SetKeyName(2, "list.gif");
            this.imageListTreeView.Images.SetKeyName(3, "library.png");
            // 
            // tabPageMigrationPreparation
            // 
            this.tabPageMigrationPreparation.Controls.Add(this.groupBox6);
            this.tabPageMigrationPreparation.Location = new System.Drawing.Point(4, 22);
            this.tabPageMigrationPreparation.Name = "tabPageMigrationPreparation";
            this.tabPageMigrationPreparation.Size = new System.Drawing.Size(1023, 380);
            this.tabPageMigrationPreparation.TabIndex = 3;
            this.tabPageMigrationPreparation.Text = "Migration Preparation";
            this.tabPageMigrationPreparation.UseVisualStyleBackColor = true;
            // 
            // groupBox6
            // 
            this.groupBox6.Controls.Add(this.buttonStartMigration);
            this.groupBox6.Controls.Add(this.groupBox7);
            this.groupBox6.Location = new System.Drawing.Point(8, 3);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(1007, 369);
            this.groupBox6.TabIndex = 1;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "Migration Preparation";
            // 
            // buttonStartMigration
            // 
            this.buttonStartMigration.Location = new System.Drawing.Point(901, 340);
            this.buttonStartMigration.Name = "buttonStartMigration";
            this.buttonStartMigration.Size = new System.Drawing.Size(100, 23);
            this.buttonStartMigration.TabIndex = 2;
            this.buttonStartMigration.Text = "start migration";
            this.buttonStartMigration.UseVisualStyleBackColor = true;
            // 
            // groupBox7
            // 
            this.groupBox7.Controls.Add(this.listViewMigrationContent);
            this.groupBox7.Location = new System.Drawing.Point(6, 19);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(271, 334);
            this.groupBox7.TabIndex = 1;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "Migration Element Configuration";
            // 
            // listViewMigrationContent
            // 
            this.listViewMigrationContent.Location = new System.Drawing.Point(15, 19);
            this.listViewMigrationContent.MultiSelect = false;
            this.listViewMigrationContent.Name = "listViewMigrationContent";
            this.listViewMigrationContent.Size = new System.Drawing.Size(231, 299);
            this.listViewMigrationContent.SmallImageList = this.imageListMigrationContent;
            this.listViewMigrationContent.TabIndex = 3;
            this.listViewMigrationContent.UseCompatibleStateImageBehavior = false;
            this.listViewMigrationContent.View = System.Windows.Forms.View.List;
            // 
            // imageListMigrationContent
            // 
            this.imageListMigrationContent.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageListMigrationContent.ImageStream")));
            this.imageListMigrationContent.TransparentColor = System.Drawing.Color.Transparent;
            this.imageListMigrationContent.Images.SetKeyName(0, "error.png");
            this.imageListMigrationContent.Images.SetKeyName(1, "ok.png");
            // 
            // tabPageMigrationProgress
            // 
            this.tabPageMigrationProgress.Controls.Add(this.groupBox5);
            this.tabPageMigrationProgress.Location = new System.Drawing.Point(4, 22);
            this.tabPageMigrationProgress.Name = "tabPageMigrationProgress";
            this.tabPageMigrationProgress.Size = new System.Drawing.Size(1023, 380);
            this.tabPageMigrationProgress.TabIndex = 2;
            this.tabPageMigrationProgress.Text = "Migration Progress";
            this.tabPageMigrationProgress.UseVisualStyleBackColor = true;
            // 
            // groupBox5
            // 
            this.groupBox5.Controls.Add(this.listBoxMigrationLog);
            this.groupBox5.Controls.Add(this.button1);
            this.groupBox5.Location = new System.Drawing.Point(0, 0);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(1020, 375);
            this.groupBox5.TabIndex = 3;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Migration Progress";
            // 
            // listBoxMigrationLog
            // 
            this.listBoxMigrationLog.FormattingEnabled = true;
            this.listBoxMigrationLog.Location = new System.Drawing.Point(8, 19);
            this.listBoxMigrationLog.Name = "listBoxMigrationLog";
            this.listBoxMigrationLog.Size = new System.Drawing.Size(1006, 316);
            this.listBoxMigrationLog.TabIndex = 0;
            // 
            // button1
            // 
            this.button1.Enabled = false;
            this.button1.Location = new System.Drawing.Point(914, 346);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(100, 23);
            this.button1.TabIndex = 2;
            this.button1.Text = "Finish & Exit";
            this.button1.UseVisualStyleBackColor = true;
            // 
            // tabPageMigrationElements
            // 
            this.tabPageMigrationElements.Controls.Add(this.checkBoxMigrateContentType);
            this.tabPageMigrationElements.Controls.Add(this.buttonElementsMigration);
            this.tabPageMigrationElements.Controls.Add(this.labelMigrationElementsHeader);
            this.tabPageMigrationElements.Controls.Add(this.checkBoxMigrateUser);
            this.tabPageMigrationElements.Controls.Add(this.checkBoxMigrateGroup);
            this.tabPageMigrationElements.Controls.Add(this.checkBoxMigrateSiteColumns);
            this.tabPageMigrationElements.Controls.Add(this.checkBoxMigrateWorkflow);
            this.tabPageMigrationElements.Controls.Add(this.checkBoxMigratePermissionlevels);
            this.tabPageMigrationElements.Location = new System.Drawing.Point(4, 22);
            this.tabPageMigrationElements.Name = "tabPageMigrationElements";
            this.tabPageMigrationElements.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageMigrationElements.Size = new System.Drawing.Size(1023, 380);
            this.tabPageMigrationElements.TabIndex = 4;
            this.tabPageMigrationElements.Text = "Migration Elements";
            this.tabPageMigrationElements.UseVisualStyleBackColor = true;
            // 
            // checkBoxMigrateContentType
            // 
            this.checkBoxMigrateContentType.AutoSize = true;
            this.checkBoxMigrateContentType.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.checkBoxMigrateContentType.Location = new System.Drawing.Point(64, 79);
            this.checkBoxMigrateContentType.Name = "checkBoxMigrateContentType";
            this.checkBoxMigrateContentType.Size = new System.Drawing.Size(148, 17);
            this.checkBoxMigrateContentType.TabIndex = 7;
            this.checkBoxMigrateContentType.Text = "Migrate Content-Type";
            this.checkBoxMigrateContentType.UseVisualStyleBackColor = true;
            this.checkBoxMigrateContentType.CheckedChanged += new System.EventHandler(this.checkBoxMigrateContentType_CheckedChanged);
            // 
            // buttonElementsMigration
            // 
            this.buttonElementsMigration.Location = new System.Drawing.Point(244, 321);
            this.buttonElementsMigration.Name = "buttonElementsMigration";
            this.buttonElementsMigration.Size = new System.Drawing.Size(183, 23);
            this.buttonElementsMigration.TabIndex = 6;
            this.buttonElementsMigration.Text = "Start Migration Elements";
            this.buttonElementsMigration.UseVisualStyleBackColor = true;
            this.buttonElementsMigration.Click += new System.EventHandler(this.buttonElementsMigration_Click);
            // 
            // labelMigrationElementsHeader
            // 
            this.labelMigrationElementsHeader.AutoSize = true;
            this.labelMigrationElementsHeader.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelMigrationElementsHeader.Location = new System.Drawing.Point(54, 27);
            this.labelMigrationElementsHeader.Name = "labelMigrationElementsHeader";
            this.labelMigrationElementsHeader.Size = new System.Drawing.Size(189, 24);
            this.labelMigrationElementsHeader.TabIndex = 5;
            this.labelMigrationElementsHeader.Text = "Migration Elements";
            // 
            // checkBoxMigrateUser
            // 
            this.checkBoxMigrateUser.AutoSize = true;
            this.checkBoxMigrateUser.Location = new System.Drawing.Point(64, 117);
            this.checkBoxMigrateUser.Name = "checkBoxMigrateUser";
            this.checkBoxMigrateUser.Size = new System.Drawing.Size(86, 17);
            this.checkBoxMigrateUser.TabIndex = 4;
            this.checkBoxMigrateUser.Text = "Migrate User";
            this.checkBoxMigrateUser.UseVisualStyleBackColor = true;
            // 
            // checkBoxMigrateGroup
            // 
            this.checkBoxMigrateGroup.AutoSize = true;
            this.checkBoxMigrateGroup.Location = new System.Drawing.Point(64, 156);
            this.checkBoxMigrateGroup.Name = "checkBoxMigrateGroup";
            this.checkBoxMigrateGroup.Size = new System.Drawing.Size(93, 17);
            this.checkBoxMigrateGroup.TabIndex = 3;
            this.checkBoxMigrateGroup.Text = "Migrate Group";
            this.checkBoxMigrateGroup.UseVisualStyleBackColor = true;
            // 
            // checkBoxMigrateSiteColumns
            // 
            this.checkBoxMigrateSiteColumns.AutoSize = true;
            this.checkBoxMigrateSiteColumns.Location = new System.Drawing.Point(64, 234);
            this.checkBoxMigrateSiteColumns.Name = "checkBoxMigrateSiteColumns";
            this.checkBoxMigrateSiteColumns.Size = new System.Drawing.Size(122, 17);
            this.checkBoxMigrateSiteColumns.TabIndex = 2;
            this.checkBoxMigrateSiteColumns.Text = "Migrate SiteColumns";
            this.checkBoxMigrateSiteColumns.UseVisualStyleBackColor = true;
            // 
            // checkBoxMigrateWorkflow
            // 
            this.checkBoxMigrateWorkflow.AutoSize = true;
            this.checkBoxMigrateWorkflow.Location = new System.Drawing.Point(64, 269);
            this.checkBoxMigrateWorkflow.Name = "checkBoxMigrateWorkflow";
            this.checkBoxMigrateWorkflow.Size = new System.Drawing.Size(109, 17);
            this.checkBoxMigrateWorkflow.TabIndex = 1;
            this.checkBoxMigrateWorkflow.Text = "Migrate Workflow";
            this.checkBoxMigrateWorkflow.UseVisualStyleBackColor = true;
            // 
            // checkBoxMigratePermissionlevels
            // 
            this.checkBoxMigratePermissionlevels.AutoSize = true;
            this.checkBoxMigratePermissionlevels.Location = new System.Drawing.Point(64, 197);
            this.checkBoxMigratePermissionlevels.Name = "checkBoxMigratePermissionlevels";
            this.checkBoxMigratePermissionlevels.Size = new System.Drawing.Size(145, 17);
            this.checkBoxMigratePermissionlevels.TabIndex = 0;
            this.checkBoxMigratePermissionlevels.Text = "Migrate PermissionLevels";
            this.checkBoxMigratePermissionlevels.UseVisualStyleBackColor = true;
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1031, 433);
            this.Controls.Add(this.tabControMain);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "MainForm";
            this.Text = "Sharezbold-UI";
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.tabControMain.ResumeLayout(false);
            this.tabPageConfiguration.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.tabPageContentSelection.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.tabPageMigrationPreparation.ResumeLayout(false);
            this.groupBox6.ResumeLayout(false);
            this.groupBox7.ResumeLayout(false);
            this.tabPageMigrationProgress.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.tabPageMigrationElements.ResumeLayout(false);
            this.tabPageMigrationElements.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem dateiToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox textBoxFromHost;
        private System.Windows.Forms.TextBox textBoxFromUserName;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox textBoxFromDomain;
        private System.Windows.Forms.TextBox textBoxFromPassword;
        private System.Windows.Forms.Button buttonConfigurationNext;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TreeView treeViewContentSelection;
        private System.Windows.Forms.ListBox listBoxMigrationLog;
        private System.Windows.Forms.ToolStripMenuItem loadMigrationProfileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem saveMigrationProfileToolStripMenuItem;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox textBoxToHost;
        private System.Windows.Forms.TextBox textBoxToUserName;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox textBoxToDomain;
        private System.Windows.Forms.TextBox textBoxToPassword;
        private System.Windows.Forms.TabControl tabControMain;
        private System.Windows.Forms.TabPage tabPageConfiguration;
        private System.Windows.Forms.TabPage tabPageContentSelection;
        private System.Windows.Forms.TabPage tabPageMigrationProgress;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.ImageList imageListTreeView;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem saveMigrationProfileToolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem loadMigrationProfileToolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem closeToolStripMenuItem;
        private System.Windows.Forms.TabPage tabPageMigrationPreparation;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.GroupBox groupBox7;
        private System.Windows.Forms.Button buttonConfigureMigration;
        private System.Windows.Forms.Button buttonStartMigration;
        private System.Windows.Forms.ListView listViewMigrationContent;
        private System.Windows.Forms.ImageList imageListMigrationContent;
        private System.Windows.Forms.TabPage tabPageMigrationElements;
        private System.Windows.Forms.Button buttonElementsMigration;
        private System.Windows.Forms.Label labelMigrationElementsHeader;
        private System.Windows.Forms.CheckBox checkBoxMigrateUser;
        private System.Windows.Forms.CheckBox checkBoxMigrateGroup;
        private System.Windows.Forms.CheckBox checkBoxMigrateSiteColumns;
        private System.Windows.Forms.CheckBox checkBoxMigrateWorkflow;
        private System.Windows.Forms.CheckBox checkBoxMigratePermissionlevels;
        private System.Windows.Forms.CheckBox checkBoxMigrateContentType;
    }
}